<!DOCTYPE html>
<html lang="en">
<head>
<meta content="width=device-width, initial-scale=1" name="viewport">
<title>Not Found</title>
<link rel="stylesheet" href="/assets/errors-aad858e5e6ec4f73ee471de09e5b2534823600677f9fb23bbcf136c108de8e6b.css" />
<link rel="stylesheet" href="/assets/application-98174c41b106a15dc514fc44bfe968dc367ce0071e2ae24448ef319bd7f85fe8.css" />
<link rel="stylesheet" href="/assets/fonts-deb7ad1d55ca77c0172d8538d53442af63604ff490c74acc2859db295c125bdb.css" />
<link rel="stylesheet" href="/assets/tailwind-9e0be7f98974eaf917dee926d5ec7f4677a12c2701315975b085a3cc918ea3ab.css" />
</head>
<body>
<div class="page-container">
<div class="error-container">
<img alt="404" src="/assets/illustrations/error/error-404-lg-9dfb20cc79e1fe8104e0adb122a710283a187b075b15187e2f184d936a16349c.svg" />
<h1>
404: Page not found
</h1>
<p>
Make sure the address is correct and the page has not moved.
Please contact your GitLab administrator if you think this is a mistake.
</p>
<div class="action-container">
<form class="form-inline-flex" action="/search" accept-charset="UTF-8" method="get"><div class="field">
<input type="search" name="search" id="search" value="" placeholder="Search for projects, issues, etc." class="form-control" />
</div>
<button type="submit" class="gl-button btn btn-md btn-confirm "><span class="gl-button-text">
Search

</span>

</button></form></div>
<nav>
<ul class="error-nav">
<li>
<a href="/">Home</a>
</li>
<li>
<a href="/users/sign_in?redirect_to_referer=yes">Sign In / Register</a>
</li>
<li>
<a href="/help">Help</a>
</li>
</ul>
</nav>

</div>

</div>
<script nonce="sr2D9XrAkxcxzy5H0MQHPA==">
//<![CDATA[
(function(){
  var goBackElement = document.querySelector('.js-go-back');

  if (goBackElement && history.length > 1) {
    goBackElement.removeAttribute('hidden');

    goBackElement.querySelector('button').addEventListener('click', function() {
      history.back();
    });
  }

  // We do not have rails_ujs here, so we're manually making a link trigger a form submit.
  document.querySelector('.js-sign-out-link')?.addEventListener('click', (e) => {
    e.preventDefault();
    document.querySelector('.js-sign-out-form')?.submit();
  });
}());

//]]>
</script></body>
</html>
