# coding: utf-8

# flake8: noqa

"""
    Minimal GitLab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Project",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from openapi_client.api.default_api import DefaultApi as DefaultApi
    
    # import ApiClient
    from openapi_client.api_response import ApiResponse as ApiResponse
    from openapi_client.api_client import ApiClient as ApiClient
    from openapi_client.configuration import Configuration as Configuration
    from openapi_client.exceptions import OpenApiException as OpenApiException
    from openapi_client.exceptions import ApiTypeError as ApiTypeError
    from openapi_client.exceptions import ApiValueError as ApiValueError
    from openapi_client.exceptions import ApiKeyError as ApiKeyError
    from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
    from openapi_client.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from openapi_client.models.project import Project as Project
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from openapi_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.project import Project as Project

""",
            name=__name__,
            doc=__doc__,
        )
    )
